[workspace]

members = [
    "udp_wrapper",
    "http_server",
    "config_simple",
    "smart_house_lib",
    "smart_rosette",
    "smart_thermometer",
    "smart_house_gui",
    "tcp_wrapper",
    "tcp_server"
]